apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api

commonAnnotations:
  cluster: aks01-prod.westeurope.cloudapp.azure.com
  environment: prod

images:
  - name: jsoliveira/.*
    newTag: develop.v2 


bases:
  - ../services/multiplication
  - ../services/subtraction
  - ../services/calculator
  - ../services/division
  - ../services/addition

resources:
  - namespace.yaml

replacements:
  - source:
      kind: Ingress
      fieldPath: metadata.annotations.cluster
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /metadata/annotations/fluxcd.io~1tag.app
        value: glob:master-*