apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../.template/api
images:
  - name: <template>
<<<<<<< HEAD
    newName: jsoliveira/api-services-calculator
    newTag: master.v3
=======
    newName: jsoliveira/api-service-calculator
<<<<<<< HEAD
    newTag: master.v12
>>>>>>> 9a873c5 ([skip ci] merged master into master)
=======
    newTag: master.v13
>>>>>>> 159c318 ([skip ci] merged master into master)
commonLabels:
  name: calculator
replacements:
  - source:
      kind: Deployment
      fieldPath: metadata.labels.name
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.name
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
          - spec.template.spec.containers.0.name
      - select:
          kind: Service
        fieldPaths:
          - metadata.name
          - spec.selector.app
