apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../.template/api
images:
  - name: <template>
    newName: jsoliveira/api-service-client
    newTag: master.v3
commonLabels:
  app: client
replacements:
  - source:
      kind: Deployment
      fieldPath: metadata.labels.app
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.name
          - spec.template.metadata.labels.app
          - spec.template.spec.containers.0.name
      - select:
          kind: Service
        fieldPaths:
          - metadata.name
          - spec.selector.app
patchesStrategicMerge:
  - volumes.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: client-config
    files:
      - config.json
        